### ISSUE TITLE
Weird model geometry

### ISSUE THREAD

**Issue by hungpham2511** [stephane-caron/topp-mpc#1]
Hi Stephane,

While playing around with topp-mpc (via walk.py) I have the "Crazy model geometry" issue
again. 

https://github.com/rdiankov/openrave/issues/435

![crazy_model](https://user-images.githubusercontent.com/9715532/27162201-99244218-51b2-11e7-9125-0ebd298f34f0.png)

Were you able to handle it somehow? I know the trick: "Load model first, then set Viewer" already though.

Hung

**Comment by stephane-caron** [comment]
Thanks Hung. Indeed, the version of *pymanoid* shipped with this project is a bit outdated. For now I pushed a fix for this problem. Later on, I will bring the code up-to-date with the latest *pymanoid*.

**Comment by minhson0307** [comment]
ong anh oi. fix duoc loi  nay chua. chi em voi @@ @hungpham2511

**Comment by hungpham2511** [comment]
Hi MinSon, mình cũng không rõ có cách nào khác.

Hi Mínon, I am not sure if there is another way to address this issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by minhson0307** [comment]
@hungpham2511 vay khong sua duoc loi  nay ha anh

**Comment by hungpham2511** [comment]
Yes, bạn có thể làm trick load model trước rồi mới set viewer.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by minhson0307** [comment]
anh ơi, chỉ dùm em mấy cái trick load luôn đi anh T.T e mới học có biết gì đâu

**Comment by hungpham2511** [comment]
Không có gì phức tạp cả, bạn cứ load model trước rồi mới gọi openrave viewer ra thì sẽ k bị lỗi đó.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by minhson0307** [comment]
cám ơn anh nhé. để em làm thử. có gì e lại hỏi. hehe
